# SonarCloud Project Configuration

sonar.organization=michal-piotrkowski
sonar.projectKey=pk.ni:PASiR_Piotrkowski_Michal
sonar.projectName=PASiR_Piotrkowski_Michal

# Path to sources
sonar.sources=server/src/main/java,client/src
sonar.tests=server/src/test
sonar.sourceEncoding=UTF-8

# Path to compiled binaries
sonar.java.binaries=server/target/classes
sonar.java.test.binaries=server/target/test-classes

# Exclusions
sonar.exclusions=**/node_modules/**,client/dist/**,server/target/**
