spring.application.name=PASiR_Piotrkowski_Michal

spring.config.import=optional:file:.env[.properties]

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/piotrkowski_michal_k03_spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
spring.datasource.username=user-ni
spring.datasource.password=strongUserPass123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#GraphQL
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls
spring.graphql.graphiql.enabled=true